// Code generated by protoc-gen-go.
// source: packet.proto
// DO NOT EDIT!

/*
Package packet is a generated protocol buffer package.

It is generated from these files:
	packet.proto

It has these top-level messages:
	EmailMessageWithByteArray
	EmailMessageWithByteArrayPacket
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type EmailMessageWithByteArray struct {
	Sender     *string  `protobuf:"bytes,1,opt,name=Sender" json:"Sender,omitempty"`
	Recipients []string `protobuf:"bytes,2,rep,name=Recipients" json:"Recipients,omitempty"`
	EmlData    []byte   `protobuf:"bytes,3,opt,name=EmlData" json:"EmlData,omitempty"`
	MessageId  *string  `protobuf:"bytes,4,opt,name=MessageId" json:"MessageId,omitempty"`
	//XXX_unrecognized []byte   `json:"-"`
}

func (m *EmailMessageWithByteArray) Reset()         { *m = EmailMessageWithByteArray{} }
func (m *EmailMessageWithByteArray) String() string { return proto.CompactTextString(m) }
func (*EmailMessageWithByteArray) ProtoMessage()    {}

func (m *EmailMessageWithByteArray) GetSender() string {
	if m != nil && m.Sender != nil {
		return *m.Sender
	}
	return ""
}

func (m *EmailMessageWithByteArray) GetRecipients() []string {
	if m != nil {
		return m.Recipients
	}
	return nil
}

func (m *EmailMessageWithByteArray) GetEmlData() []byte {
	if m != nil {
		return m.EmlData
	}
	return nil
}

func (m *EmailMessageWithByteArray) GetMessageId() string {
	if m != nil && m.MessageId != nil {
		return *m.MessageId
	}
	return ""
}

type EmailMessageWithByteArrayPacket struct {
	Messages []*EmailMessageWithByteArray `protobuf:"bytes,1,rep,name=Messages" json:"Messages,omitempty"`
	//XXX_unrecognized []byte                       `json:"-"`
}

func (m *EmailMessageWithByteArrayPacket) Reset()         { *m = EmailMessageWithByteArrayPacket{} }
func (m *EmailMessageWithByteArrayPacket) String() string { return proto.CompactTextString(m) }
func (*EmailMessageWithByteArrayPacket) ProtoMessage()    {}

func (m *EmailMessageWithByteArrayPacket) GetMessages() []*EmailMessageWithByteArray {
	if m != nil {
		return m.Messages
	}
	return nil
}
